---
  - name: test and install IIS 
    hosts: all
    vars:
      iis_test_message: "Hello, world!"
    tasks:
      - name: Stop the play if the host is not a Windows system
        ansible.builtin.meta: end_host
        when: ansible_facts['os_family'] is not defined or ansible_facts['os_family'] != "Windows"     # Other options: RedHat, Darwin

      - name: install iis
        ansible.windows.win_feature:
          name: Web-Server
          state: present
  
      - name: start iis service
        ansible.windows.win_service:
          name: W3Svc
          state: started
  
      - name: Create website index.html
        ansible.windows.win_copy:
          content: "{{ iis_test_message }}"
          dest: C:\Inetpub\wwwroot\index.html
  
      - name: Check for 200 response from IIS and that content is as expected
        ansible.builtin.uri:
          url: "http://{{ hostvars[inventory_hostname]['ansible_ip_addresses'][0] }}"
          return_content: yes
        register: response 
        delegate_to: localhost
        failed_when: iis_test_message not in response.content

      - name: Show website address
        ansible.builtin.debug:
          msg: http://{{ ansible_host }}
