---
- name: This is my Windows patching playbook
  hosts: "{{ hostlist | default('all') }}"
  tasks:
    - name: Stop the play if the host is not a Windows system
      ansible.builtin.meta: end_host
      when: ansible_facts['os_family'] is not defined or ansible_facts['os_family'] != "Windows"     # Other options: RedHat, Darwin

    - name: Install Windows Updates
      ansible.windows.win_updates:
        category_names: "{{ categories | default(omit) }}"
        reboot: '{{ reboot_server | default(yes) }}'
